### ISSUE TITLE
Documentation and/or instructuions

### ISSUE THREAD

**Issue by gdevenyi** [jelman/SKM_cluster#5]
Hello, I'd like to use SKM_cluster but I can't find any examples of how to actually use this tool, can you assist?

**Comment by jelman** [comment]
Hi Gabriel,

We had actually taken a break from working on this tool before it was
finished, and therefore wouldn't recommend using it in its current form.
There had been a bug in rpy2 that caused a crash every once in awhile, and
the results were showing somewhat of a bias towards over-classifying
subjects into our PIB+ group.

In a couple weeks I should have time to put together some more
documentation. In the meantime, I have included the papers describing the
methods we were trying to implement.

I'll update you when I get a chance to work on this a bit more.

Best,
Jeremy
